### ISSUE TITLE
Subscription fails if not HTTPS

### ISSUE THREAD

**Issue by colegleason** [SamyPesse/glass.py#9]
I get the following error when trying to log in (after login success, trying to subscribe):

```
Traceback (most recent call last):
  File "/home/cole/code/vision/venv/lib/python2.7/site-packages/flask/app.py", line 1701, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/cole/code/vision/venv/lib/python2.7/site-packages/flask/app.py", line 1689, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/cole/code/vision/venv/lib/python2.7/site-packages/flask/app.py", line 1687, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/cole/code/vision/venv/lib/python2.7/site-packages/flask/app.py", line 1360, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/cole/code/vision/venv/lib/python2.7/site-packages/flask/app.py", line 1358, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/cole/code/vision/venv/lib/python2.7/site-packages/flask/app.py", line 1344, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/cole/code/vision/venv/lib/python2.7/site-packages/glass/app.py", line 76, in _oauth_callback
    self.subscriptions.init_user(user)
  File "/home/cole/code/vision/venv/lib/python2.7/site-packages/glass/subscriptions.py", line 114, in init_user
    "callbackUrl": callback_url
  File "/home/cole/code/vision/venv/lib/python2.7/site-packages/glass/user.py", line 58, in request
    raise e
HTTPError: 400 Client Error: Bad Request
```

Response:

```
{\n "error": {\n  "errors": [\n   {\n    "domain": "global",\n    "reason": "invalid",\n    "message": "callbackUrl must be a valid HTTPS URL"\n   }\n  ],\n  "code": 400,\n  "message": "callbackUrl must be a valid HTTPS URL"\n }\n}\n
```

**Comment by colegleason** [comment]
Maybe needs to support the subscription proxy:
https://developers.google.com/glass/subscription-proxy
